Feature #13789: improving performances into blog loading data.
Silverpeas/Silverpeas-Components pull request #849
Opened 2024-01-16 17:18 UTC by SilverYoCha

2024-01-22 16:17 UTC, mmoqui requested changes
I ask for renaming some original method names. It is for a better understanding for both new developers and for those who get back to the code months or years later. We have to establish a clear distinction between a blog post and an event that can be related by such a post; a post isn't an event, it creates an event (in the calendar of the blog): either the event about which its content is or the event of the post writing itself.

2024-01-22 16:17 UTC, mmoqui commented on blog/blog-library/src/main/java/org/silverpeas/components/blog/service/DefaultBlogService.java
> +      Collection<String> lastEventIds = PostDAO.getAllEvents(con, instanceId);
Pfff, this method name was originally misnamed. In fact, what this method does is to get all the blog posts of the specified component instance ordered by their event date. So the method should be renamed to something like `getAllPostsOrderedByEventDate`.
And then the variable shouldn't be named lastEventIds but something like `postsOrderedByEventDate`.

My remark is also for all similar snippet of code written in the next methods below (this allow me to not repeat this comment)

2024-01-23 09:06 UTC, SilverYoCha commented on blog/blog-library/src/main/java/org/silverpeas/components/blog/dao/PostDAO.java
>    public static Collection<String> getEventsByDates(Connection con, String instanceId,
Signature has been renamed.

2024-01-23 09:06 UTC, SilverYoCha commented on blog/blog-library/src/main/java/org/silverpeas/components/blog/service/BlogFilters.java
> +  public BlogFilters withMaxResultOf(final int maxResult) {
OK

2024-01-23 09:06 UTC, SilverYoCha commented on blog/blog-library/src/main/java/org/silverpeas/components/blog/service/BlogService.java
> +  Collection<PostDetail> getPostsByCategory(String categoryId, String instanceId,
OK

2024-01-23 09:07 UTC, SilverYoCha commented on blog/blog-library/src/main/java/org/silverpeas/components/blog/service/DefaultBlogService.java
> +  private Map<String, Date> getDateByEvents(Collection<String> pubIds) {
Signature has been renamed.

2024-01-24 13:11 UTC, merged